on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true   # Speeds up CRAN package installs

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c(
            "data.table",
            "survival",
            "broom",
            "mlr3",
            "mlr3learners",
            "mlr3proba",
            "mlr3fselect",
            "lattice",
            "rmarkdown",
            "knitr"
          ))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: report.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
